config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'home',            to:"desafio#home"
  get 'projects',        to:"desafio#projects"
  get 'contact',         to:"desafio#contact"
  # Defines the root path route ("/")
  
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/desafio_controller.rb
class DesafioController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desafio_helper.rb
module DesafioHelper
end

app/views/desafio/contact.html.erb
<h1>Desafio#contact</h1>
<p>Find me in app/views/desafio/contact.html.erb</p>

app/views/desafio/home.html.erb
<h1>Desafio#home</h1>
<p>Find me in app/views/desafio/home.html.erb</p>

app/views/desafio/projects.html.erb
<h1>Desafio#projects</h1>
<p>Find me in app/views/desafio/projects.html.erb</p>

<div class="tarjetas">
<div class="row">
<div class="col">
<div class="card" style="width: 18rem; class: 'h-100'">
  <%= image_tag 'suricata.jpg', class:'card-img-top'  %>
  <div class="card-body">
    <h5 class="card-title">Proyecto Suricata</h5>
    <p class="card-text">Proyecto acerca ed una empresa de comida casera</p>
    <a href="https://github.com/SebitaMiranda/proyecto_suricata" class="btn btn-primary">Ver Mas</a>
  </div>
</div>
</div>
<div class="col">
<div class="card" style="width: 18rem; class: 'h-100'">
<%= image_tag 'metandcof.jpg', class: 'card-img-top' %>
  <div class="card-body">
    <h5 class="card-title">Proyecto Meet and Coffee</h5>
    <p class="card-text">Aprende y analiza tomando cafe</p>
    <a href="https://sebitamiranda.github.io/meet-coffee/" class="btn btn-primary">Ver Mas</a>
  </div>
</div>
</div>
  <div class="col">
 <div class="card" style="width: 18rem; class: 'h-100'">
 <%= image_tag 'olivia ros.jpg', class: 'card-img-top' %>
  <div class="card-body">
    <h5 class="card-title">Proyecto Olica Ross</h5>
    <p class="card-text">Pagina personal de Oliva Ross</p>
    <a href="https://github.com/SebitaMiranda/viajes_chile" class="btn btn-primary">Ver Mas</a>
  </div>
 </div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to 'Home', home_path, class: 'nav-link active' %>
        <%= link_to 'Projects', projects_path, class: 'nav-link' %>
        <%= link_to 'Contact', contact_path, class: 'nav-link' %>
      </div>
    </div>
  </div>
</nav>

    <%= yield %>

 





    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>